### ISSUE TITLE
generate documentation from the code

### ISSUE THREAD

**Issue by flynneva** [Tritron-Robotics/robotcode2022#5]
Automatic documentation generation is possible by following some simple rules with comments within code.  This can help keep track of project as more and more things are added.

It looks like [`javadoc`](https://www.baeldung.com/javadoc) is our best bet for generating some documentation from the code.

[See here (WPIRobotics GRIP project) for an example on a github action that generates some docs](https://github.com/WPIRoboticsProjects/GRIP/actions/runs/243955028/workflow)

- [x] generate some basic docs using `javadoc` with a github action

**Comment by An3Dev** [comment]
I setup the repo to automatically generate documentation and publish it on github pages every time that we push code to the main branch. I created an orphan branch called gh-pages. When code is pushed to the main branch, the Deploy Javadoc workflow generates the javadoc files, and publishes them to the gh-pages branch. Then, the pages-build-deployment workflow runs because it detects that there were changes to the gh-pages branch. It builds and deploys the website.

**Comment by flynneva** [comment]
@An3Dev awesome stuff! This will be great for new people to the software team to look over the code base more easily, also it helps existing developers better understand how the code is structured.

Link to the website: https://tritron-robotics.github.io/robotcode2022/
